version: '3.9'

services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - foodcore-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/oracle@localhost:1521/XE"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s

  foodcore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodcore
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - foodcore-network

networks:
  foodcore-network:
    driver: bridge

volumes:
  oracle-data: