version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: system
      APP_USER: FoodCore
      APP_USER_PASSWORD: FoodCore123
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/system@localhost/XE"]
      interval: 10s
      timeout: 5s
      retries: 5

  foodcore-app:
    image: foodcore-foodcore-app:latest
    build: .
    container_name: foodcore
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@localhost:1521/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: system
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate